### ISSUE TITLE
Where are the contents stored?

### ISSUE THREAD

**Issue by chaoscommander** [danielroehrig/diary#58]
Hello, I just started using Diary and I wonder where the entered texts go? I'd like to be able to make a backup and restore it if needed. I looked for any relevant folders/files but didn't find any.

**Comment by Sallyje** [comment]
its in the nextcloud database.
you can also back up from the settings at the bottom

**Comment by danielroehrig** [comment]
What @Sallyje said. You can back up the entries either directly through the app or if you have access to the database look for a diary table.

**Comment by chaoscommander** [comment]
Ah, great. Thanks!

**Comment by stellarpower** [comment]
Would it be worth considering storage on the filesystem - as a file or folder? This could allow first-class sharing of diaries, downloading, saving multiple diaries in different locations, etc. The GUI editor could then be opened like a MIME file type association of diary files, perhaps in addition to being available as an app on its own (in which case previously-opened diary files could be made available from a drop-down/list/tree/similar.

I have used [RedNotebook](https://rednotebook.app/) on my desktop; this stores as a simple folder managed by month, and markdown files named with the given date. I think a simple format like this (e.g. zipping these up) would make sense if possible - perhaps any further metadata required a the root level in some JSON.

Cheers!

**Comment by danielroehrig** [comment]
I didn't want to use the file system because I didn't like the way it worked in the cookbook extension that I added a couple of lines to. A database is so much easier to maintain than files. I get the appeal, especially in nextcloud which was made to work with files, but for me it's just ... messy.

**Comment by TristanCottam** [comment]
> I didn't want to use the file system because I didn't like the way it worked in the cookbook extension that I added a couple of lines to.

Could you elaborate on what you disliked about file-based storage? I agree with @stellarpower that this would make for much nicer integration within Nextcloud's ecosystem.

**Comment by danielroehrig** [comment]
I don't know much about CalDav or the way Nextcloud uses the file system but the cookbook extension is working fine, so it can't be that bad. I know my way around a database, so that's what I used. I will continue to port the app to newer versions of Nextcloud but to be honest, if nobody wants to help me with the frontend, I won't be adding more features or do big changes. I can't dump hours into this project to align three pixels.

For me, this app does what I need it to do. I want it to stay around. And I would absolutely not mind adding some features. But not without any help.
